server:
  port: 8090

spring:
  application:
    name: msvc-auth
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  config:
    import: optional:configserver:http://localhost:8888 # path del config server
jwt:
  expiration: 3600000
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka