eureka:
  client:
    register-with-eureka: false # no se registra dentro del servidor de eureka

server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: users
          uri: lb://msvc-users
          predicates:
            - Path=/api/users/**
        - id: patrols
          uri: lb://msvc-patrols
          predicates:
            - Path=/api/patrols/**
        - id: incidents
          uri: lb://msvc-incidents
          predicates:
            - Path=/api/incidents/**
        - id: auth
          uri: lb://msvc-auth
          predicates:
            - Path=/api/auth/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG