server:
  port: 8082
#  error:
#    include-message: always

spring:
  application:
    name: msvc-users
  config:
    import: optional:configserver:http://localhost:8888 # path del config server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/msvc_users_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
